import CoreGraphics
import Foundation
import Testing
@testable import Canvas

@Suite("ElementInspectorData")
struct ElementInspectorDataTests {

  @Test func initStoresAllProperties() {
    let id = UUID()
    let rect = CGRect(x: 10, y: 20, width: 300, height: 50)
    let styles = ["color": "red", "fontSize": "14px"]
    let data = ElementInspectorData(
      id: id,
      tagName: "SPAN",
      elementId: "title",
      className: "heading bold",
      textContent: "Hello",
      outerHTML: "<span>Hello</span>",
      cssSelector: "div > span.heading",
      computedStyles: styles,
      boundingRect: rect
    )
    #expect(data.id == id)
    #expect(data.tagName == "SPAN")
    #expect(data.elementId == "title")
    #expect(data.className == "heading bold")
    #expect(data.textContent == "Hello")
    #expect(data.outerHTML == "<span>Hello</span>")
    #expect(data.cssSelector == "div > span.heading")
    #expect(data.computedStyles == styles)
    #expect(data.boundingRect == rect)
  }

  @Test func defaultIdIsAutoGenerated() {
    let a = TestFixtures.makeMinimalDiv()
    let b = TestFixtures.makeMinimalDiv()
    #expect(a.id != b.id)
  }

  @Test func equalityBySameId() {
    let id = UUID()
    let a = TestFixtures.makeButton(id: id)
    let b = TestFixtures.makeButton(id: id)
    #expect(a == b)
  }

  @Test func inequalityByDifferentId() {
    let a = TestFixtures.makeButton(id: UUID())
    let b = TestFixtures.makeButton(id: UUID())
    #expect(a != b)
  }

  @Test func inequalityOnDifferentTagName() {
    let id = UUID()
    let a = TestFixtures.makeButton(id: id, tagName: "BUTTON")
    let b = TestFixtures.makeButton(id: id, tagName: "INPUT")
    #expect(a != b)
  }

  @Test func inequalityOnDifferentComputedStyles() {
    let id = UUID()
    let a = TestFixtures.makeButton(id: id, computedStyles: ["color": "red"])
    let b = TestFixtures.makeButton(id: id, computedStyles: ["color": "blue"])
    #expect(a != b)
  }

  @Test func inequalityOnDifferentBoundingRect() {
    let id = UUID()
    let a = TestFixtures.makeButton(id: id, boundingRect: CGRect(x: 0, y: 0, width: 100, height: 50))
    let b = TestFixtures.makeButton(id: id, boundingRect: CGRect(x: 0, y: 0, width: 200, height: 50))
    #expect(a != b)
  }

  @Test func emptyStringsAreValid() {
    let data = TestFixtures.makeMinimalDiv()
    #expect(data.elementId == "")
    #expect(data.className == "")
    #expect(data.textContent == "")
    #expect(data.outerHTML == "")
  }
}
